# Generated by Django 5.0.4 on 2024-05-29 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0002_rename_datatest_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Diary",
        ),
    ]
