# Generated by Django 5.0.4 on 2024-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0004_rename_diary_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.CharField(max_length=100)),
                ("updated_at", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=254)),
                ("longitude", models.CharField(max_length=254)),
            ],
        ),
    ]
