# Generated by Django 5.0.4 on 2024-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0005_locate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locate",
            name="created_at",
            field=models.DateTimeField(verbose_name="date published"),
        ),
        migrations.AlterField(
            model_name="locate",
            name="updated_at",
            field=models.DateTimeField(verbose_name="date published"),
        ),
    ]
