# Generated by Django 5.0.4 on 2024-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0006_alter_locate_created_at_alter_locate_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locate",
            name="created_at",
            field=models.DateTimeField(verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="locate",
            name="updated_at",
            field=models.DateTimeField(verbose_name="updated at"),
        ),
    ]
